---
title: "Learning about the world through gapminder"
subtitle: "A step-by-step guide"
author: "ds4pp"
output:
  xaringan::moon_reader:
    css: [default, metropolis-fonts] 
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false

---

```{r setup, include=FALSE}
# R options
options(
  htmltools.dir.version = FALSE, # for blogdown
  show.signif.stars = FALSE,     # for regression output
  warn = 1
  )
# figure height, width, dpi
knitr::opts_chunk$set(fig.height = 2.5, fig.width = 5, dpi = 300) 
# fontawesome
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
# magick
dev.off <- function(){
  invisible(grDevices::dev.off())
}
# code highlighting
hook_source <- knitr::knit_hooks$get('source')
knitr::knit_hooks$set(source = function(x, options) {
  x <- stringr::str_replace(x, "^[[:blank:]]?([^*].+?)[[:blank:]]*#<<[[:blank:]]*$", "*\\1")
  hook_source(x, options)
})
```



```{r packages, echo=FALSE, message=FALSE, warning=FALSE}
# Packages
library(tidyverse)
```


```{r load gapminder, include = FALSE}
library(gapminder)
```


.small[
```{r fig.width = 7, fig.height=4}
gapminder %>% filter(year == 2007) %>%
  ggplot(aes(x = gdpPercap, y = lifeExp)) +
  geom_point()
```
]

---

.small[
```{r fig.width = 7, fig.height=4}
gapminder %>% filter(year == 2007) %>%
  ggplot(aes(x = gdpPercap, y = lifeExp)) +
  geom_point() +
  labs(x = "GDP per capita", y = "Life expectancy", #<<
       title = "Life expectancy versus GDP in 2007") #<<
```
]




---

```{r fig.width = 7, fig.height=4}
gapminder %>% filter(year == 2007) %>%
  ggplot(aes(x = gdpPercap, y = lifeExp)) +
  geom_point() +
  scale_x_log10() + #<<
  labs(x = "GDP per capita", y = "Life expectancy",
       title = "Life expectancy versus GDP in 2007")
```

---

```{r fig.width = 7, fig.height=4}
gapminder %>% filter(year == 2007) %>%
  ggplot(aes(x = gdpPercap, y = lifeExp, size = pop)) + #<<
  geom_point() +
  scale_x_log10() +
  labs(x = "GDP per capita", y = "Life expectancy",
       title = "Life expectancy versus GDP in 2007")
```
---


```{r fig.width = 7, fig.height=4}
gapminder %>% filter(year == 2007) %>%
  ggplot(aes(x = gdpPercap, y = lifeExp, size = pop)) +
  geom_point(alpha = 0.5) + #<<
  scale_x_log10() +
  labs(x = "GDP per capita", y = "Life expectancy",
       title = "Life expectancy versus GDP in 2007")
```

---


```{r fig.width = 7, fig.height=4}
gapminder %>% filter(year == 2007) %>%
  ggplot(aes(x = gdpPercap, y = lifeExp, size = pop)) +
  geom_point(alpha = 0.5) + 
  scale_x_log10() +
  labs(x = "GDP per capita", y = "Life expectancy",
       title = "Life expectancy versus GDP in 2007") +
  theme_bw() #<<
```
---


```{r fig.width = 7, fig.height=4}
gapminder %>% filter(year == 2007) %>%
  ggplot(aes(x = gdpPercap, y = lifeExp, size = pop)) +
  geom_point(alpha = 0.5) +
  scale_x_log10() +
  labs(x = "GDP per capita", y = "Life expectancy",
       title = "Life expectancy versus GDP in 2007") +
  theme_bw() + 
  facet_wrap(~ continent) #<<
```

---

```{r fig.width = 7, fig.height=4}
gapminder %>% filter(year == 2007) %>%
  ggplot(aes(x = gdpPercap, y = lifeExp, size = pop, color = continent)) + #<<
  geom_point(alpha = 0.5) +
  scale_x_log10() +
  labs(x = "GDP per capita", y = "Life expectancy",
       title = "Life expectancy versus GDP in 2007") +
  theme_bw() + 
  facet_wrap(~ continent)
```


---
```{r, include = FALSE}
library(gganimate)
```

```{r fig.width = 7, fig.height=4}
gapminder %>%
   ggplot(aes(x = gdpPercap, y = lifeExp, size = pop, color = continent)) +
   geom_point(alpha = 0.5) +
   scale_x_log10() +
   labs(x = "GDP per capita", y = "Life expectancy",
        title = "Life expectancy versus GDP in {frame_time}") + #<<
   theme_bw() + 
   facet_wrap(~ continent) + 
   transition_time(year) #<<
```
